# Generated by Django 3.0.7 on 2020-11-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_C8738A28CFF7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('assets', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=30)),
                ('temperature', models.FloatField(max_length=100)),
                ('humidity', models.FloatField(max_length=100)),
            ],
            options={
                'db_table': 'thingsally',
            },
        ),
    ]
