# Generated by Django 3.0.7 on 2020-11-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='query',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
