# Generated by Django 3.0.7 on 2020-11-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_customer_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='other',
            field=models.CharField(choices=[('Application', 'Application1'), ('Application2', 'Application2'), ('Application3', 'Application3'), ('Page1', 'Page1'), ('Page2', 'Page2'), ('Page3', 'Page3')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
